# Generated by Django 3.2.4 on 2021-06-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('cell_no', models.CharField(max_length=11, null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('condition', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('cell_no', models.CharField(max_length=11, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('CP_no', models.CharField(max_length=11, null=True)),
                ('physician_notes', models.CharField(max_length=500, null=True)),
                ('physician_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.physician')),
            ],
        ),
    ]
