# Generated by Django 3.2.4 on 2021-06-25 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_physician_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups_name': 'Physician'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
