# Generated by Django 3.1.7 on 2021-10-10 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_alter_physician_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='physician_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docpatient', to='tracker.physician'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'Physician'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
