# Generated by Django 3.1.7 on 2021-10-12 12:46

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20211011_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('barangay', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('zip', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(max_length=100, null=True)),
                ('mother', models.CharField(max_length=100, null=True)),
                ('f_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='physician_assigned',
            new_name='attending_doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='physician_notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='room_no',
        ),
        migrations.AddField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nick_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
