# Generated by Django 3.1.7 on 2021-10-12 13:36

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20211012_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='CP_no',
        ),
        migrations.AddField(
            model_name='parents',
            name='f_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parents',
            name='m_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.parents'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cell_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
