# Generated by Django 3.1.7 on 2021-10-12 13:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20211012_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='f_contact',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='f_email',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='father',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='m_contact',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='mother',
        ),
        migrations.AddField(
            model_name='parents',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='parents',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parents',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parents',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
