# Generated by Django 3.1.7 on 2021-10-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20211012_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='parents',
            field=models.ForeignKey(max_length=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.parents'),
        ),
    ]
