# Generated by Django 3.1.7 on 2021-10-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20211012_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='house_no',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='parents',
        ),
        migrations.AddField(
            model_name='patient',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father', to='tracker.parents'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='tracker.parents'),
        ),
    ]
