# Generated by Django 3.1.7 on 2021-10-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20211016_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='father',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mother',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
