# Generated by Django 3.1.7 on 2021-10-18 12:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20211018_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='patient',
            name='ccontact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='cfull_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='relation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
