# Generated by Django 3.1.7 on 2021-10-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20211018_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='suffix',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
