# Generated by Django 3.1.7 on 2021-10-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_patient_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='suffix',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
