# Generated by Django 3.1.7 on 2021-10-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20211027_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
