# Generated by Django 3.1.7 on 2021-10-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_remove_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Bl', 'Blank'), ('Co', 'Confirmed'), ('Ca', 'Cancelled'), ('Rs', 'Rescheduled'), ('Rq', 'Requested')], max_length=2, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('visit', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.physician')),
            ],
        ),
    ]
