# Generated by Django 3.2.4 on 2021-11-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_auto_20211028_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Blank', 'Blank'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled'), ('Requested', 'Requested')], max_length=100, null=True),
        ),
    ]
