# Generated by Django 3.2.4 on 2021-11-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
    ]
