# Generated by Django 3.2.4 on 2021-11-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_patient_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cert_date',
            field=models.DateField(null=True),
        ),
    ]
