# Generated by Django 3.1.7 on 2021-11-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_patient_cert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
