# Generated by Django 3.1.7 on 2021-11-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_auto_20211107_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cert_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
