# Generated by Django 3.1.7 on 2021-11-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_auto_20211107_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('dose', models.CharField(max_length=50, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('location', models.CharField(choices=[('R thigh', 'R thigh'), ('L thigh', 'L thigh'), ('R arm ', 'R arm'), ('L arm', 'L arm'), ('R buttocks', 'R buttocks'), ('L buttocks', 'L buttocks')], max_length=50, null=True)),
                ('remarks', models.CharField(max_length=50, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.patient')),
            ],
        ),
    ]
