# Generated by Django 3.1.7 on 2021-11-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0040_auto_20211116_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='location',
            field=models.CharField(blank=True, choices=[('R thigh', 'R thigh'), ('L thigh', 'L thigh'), ('R arm ', 'R arm'), ('L arm', 'L arm'), ('R buttocks', 'R buttocks'), ('L buttocks', 'L buttocks')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
