# Generated by Django 3.2.4 on 2021-11-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_auto_20211116_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.patient'),
        ),
    ]
