# Generated by Django 3.2.4 on 2021-11-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_vaccine_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='patient',
        ),
    ]
