# Generated by Django 3.2.4 on 2021-11-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0043_remove_vaccine_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physician',
            old_name='specialization',
            new_name='doc_type',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='age',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='email',
        ),
        migrations.AddField(
            model_name='physician',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physician',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physician',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physician',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
