# Generated by Django 3.2.4 on 2021-11-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0046_physician_can_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='can_reg',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
    ]
