# Generated by Django 3.1.7 on 2021-11-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0047_alter_physician_can_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
