# Generated by Django 3.1.7 on 2021-11-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0048_auto_20211128_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
